"""create initial user and company tables

Revision ID: 94d68e7833d9
Revises: 
Create Date: 2025-06-08 18:13:00.549969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d68e7833d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False, comment="Yerel veritabanındaki şirket (tenant) ID'si"),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Şirketin (tenant) adı'),
    sa.Column('keycloak_group_id', sa.UUID(), nullable=False, comment="Bu şirketi temsil eden Keycloak grubunun ID'si"),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Tenant durumu (örn: active, inactive, suspended)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_companies_keycloak_group_id', 'companies', ['keycloak_group_id'], unique=False, schema='public')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_companies_keycloak_group_id'), 'companies', ['keycloak_group_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_companies_name'), 'companies', ['name'], unique=True, schema='public')
    op.create_index(op.f('ix_public_companies_status'), 'companies', ['status'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('AGENT', 'EMPLOYEE', 'GENERAL_ADMIN', 'HELPDESK_ADMIN', 'CUSTOMER_USER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['public.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users_schema'
    )
    op.create_index(op.f('ix_users_schema_users_email'), 'users', ['email'], unique=True, schema='users_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_schema_users_email'), table_name='users', schema='users_schema')
    op.drop_table('users', schema='users_schema')
    op.drop_index(op.f('ix_public_companies_status'), table_name='companies', schema='public')
    op.drop_index(op.f('ix_public_companies_name'), table_name='companies', schema='public')
    op.drop_index(op.f('ix_public_companies_keycloak_group_id'), table_name='companies', schema='public')
    op.drop_index('ix_companies_name', table_name='companies', schema='public')
    op.drop_index('ix_companies_keycloak_group_id', table_name='companies', schema='public')
    op.drop_table('companies', schema='public')
    # ### end Alembic commands ###
