# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
  paths:
    include: ['user_service/*', 'ticket_service/*', 'auth_service/*', 'frontend/*']
    exclude: [README.md]

pool:
  name: 'RKE2'

# DÜZELTME: Pipeline'ın Library'deki değişken grubunu kullanmasını sağlıyoruz.
variables:
- group: SonarQube-Variables # Adım 1'de oluşturduğumuz grubun adı
- group: Redmine-Integration
- name: harborRepo
  value: 'harbor.cloudpro.com.tr/helpdesk'
- name: imageTag
  value: '$(Build.BuildId)'
- name: k8sNamespace
  value: 'ado-agents'
- name: gitRepoUrl
  value: 'https://dev.azure.com/umutcelik0234/HelpDesk_App/_git/helpdesk-app-src'
- name: kanikoTemplateFile
  value: 'kaniko-pod-template.yaml'
- name: kanikoFinalFile
  value: '$(Build.ArtifactStagingDirectory)/kaniko-pod-final'
- name: dockerRegistryServiceConnection
  value: 'DockerHub'

stages:
- stage: Scan_And_Build_Services
  displayName: 'Scan and Build Service Images'
  jobs:
  - job: DetectChanges
    displayName: '1. Detect Changed Services'
    steps:
      - checkout: self
        fetchDepth: 0
      - task: Bash@3
        name: detect_changes_step 
        displayName: 'Run change detection script'
        inputs:
          targetType: 'inline'
          script: |
            chmod +x templates/detect-changes.sh
            ./templates/detect-changes.sh

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'user_service'
      sonarProjectKey: 'helpdesk-user-service'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.USER_SERVICE_CHANGED'], 'true')

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'ticket_service'
      sonarProjectKey: 'helpdesk-ticket-service'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.TICKET_SERVICE_CHANGED'], 'true')

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'auth_service'
      sonarProjectKey: 'helpdesk-auth-service'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.AUTH_SERVICE_CHANGED'], 'true')

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'frontend'
      sonarProjectKey: 'helpdesk-frontend'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.FRONTEND_CHANGED'], 'true')