# azure-pipelines.yml - Aşama 2: Şablonlarla Modüler Yapı

# Tetikleyici şimdilik sadece user_service için, bir sonraki aşamada bunu geliştireceğiz.
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'user_service/*'

pool:
  name: 'Default'

# Değişkenler artık pipeline genelinde tanımlı ve tüm şablonlar tarafından kullanılabilir.
variables:
  # 'harborRepo' değişkeninden servis adını kaldırdık, çünkü bu artık şablonda eklenecek.
  harborRepo: 'harbor.cloudpro.com.tr/helpdesk' 
  imageTag: '$(Build.BuildId)'
  k8sNamespace: 'ado-agents'
  gitRepoUrl: 'https://dev.azure.com/umutcelik0234/HelpDesk_App/_git/helpdesk-app-src'
  kanikoTemplateFile: 'kaniko-pod-template.yaml'
  kanikoFinalFile: '$(Build.ArtifactStagingDirectory)/kaniko-pod-final' # Servis adı olmadan temel dosya yolu.

stages:
- stage: Build_Services
  displayName: 'Build and Push Service Images'
  jobs:
    # Artık karmaşık adımlar yerine, sadece şablonu çağırıyoruz.
    - template: templates/build-service-job.yml
      parameters:
        serviceName: 'user_service'