# azure-pipelines.yml - Aşama 1 (Sözdizimi Düzeltilmiş Hali)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'user_service/*'

pool:
  name: 'Default'

variables:
  serviceName: 'user_service'
  harborRepo: 'harbor.cloudpro.com.tr/helpdesk/$(serviceName)'
  imageTag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Push Service Image'
  jobs:
  - job: BuildImage
    displayName: 'Build $(serviceName) Image'
    
    container:
      image: gcr.io/kaniko-project/executor:latest
      endpoint: HarborConnection 

    steps:
    - checkout: self

    - task: Bash@3
      displayName: 'Build and Push with Kaniko'
      # DÜZELTME: 'script' ve 'targetType' parametreleri 
      # aşağıda görüldüğü gibi bir 'inputs' bloğu içinde olmalıdır.
      inputs:
        targetType: 'inline'
        script: |
          echo "---Starting Kaniko Executor---"
          /kaniko/executor \
            --context=$(Pipeline.Workspace)/s \
            --context-sub-path=$(serviceName) \
            --dockerfile=$(Pipeline.Workspace)/s/$(serviceName)/Dockerfile \
            --destination=$(harborRepo):$(imageTag)