# azure-pipelines.yml - Final Sürüm
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'user_service/*'

pool:
  name: 'Default'

variables:
  serviceName: 'user-service'
  harborRepo: 'harbor.cloudpro.com.tr/helpdesk/$(serviceName)'
  imageTag: '$(Build.BuildId)'
  namespace: 'ado-agents'
  podName: 'kaniko-build-pod-$(imageTag)'
  k8sConnection: 'RKE2-Kubeconfig-Connection'
  
  # --- YENİ VE GÜNCEL KANIKO DEĞİŞKENLERİ ---
  # Kaniko'ya kaynak kodu hangi repodan çekeceğini söylüyoruz
  kanikoContext: 'git://https://dev.azure.com/umutcelik0234/HelpDesk_App/_git/helpdesk-app-src'
  # Reponun içinde hangi alt klasörde çalışacağını belirtiyoruz
  kanikoContextSubPath: '$(serviceName)'
  # Dockerfile yolu artık context-sub-path'e göreli
  kanikoDockerfile: 'Dockerfile'
  
  kanikoTemplateFile: '$(Build.SourcesDirectory)/kaniko-pod-template.yaml'
  kanikoFinalFile: '$(Build.ArtifactStagingDirectory)/kaniko-pod-final.yaml'

stages:
- stage: BuildWithKaniko
  displayName: 'Build and Push with Kaniko'
  jobs:
  - job: KanikoJob
    displayName: 'Build Image for $(serviceName)'
    steps:
    - task: Bash@3
      displayName: 'Create Final Kaniko Manifest from Template'
      inputs:
        targetType: 'inline'
        script: |
          cp "$(kanikoTemplateFile)" "$(kanikoFinalFile)"
          
          # sed komutları yeni değişkenlerimizi kullanacak şekilde güncellendi
          sed -i "s|__POD_NAME__|$(podName)|g" "$(kanikoFinalFile)"
          sed -i "s|__CONTEXT__|$(kanikoContext)|g" "$(kanikoFinalFile)"
          sed -i "s|__CONTEXT_SUB_PATH__|$(kanikoContextSubPath)|g" "$(kanikoFinalFile)"
          sed -i "s|__DOCKERFILE__|$(kanikoDockerfile)|g" "$(kanikoFinalFile)"
          sed -i "s|__DESTINATION_TAG__|$(harborRepo):$(imageTag)|g" "$(kanikoFinalFile)"
          sed -i "s|__DESTINATION_LATEST__|$(harborRepo):latest|g" "$(kanikoFinalFile)"
          
          echo "Final Kaniko pod manifest:"
          cat "$(kanikoFinalFile)"

    # Adım 2: Önceki adımda oluşturduğumuz nihai ve temiz YAML dosyasını uygula.
    - task: Kubernetes@1
      displayName: 'Apply Kaniko Pod Manifest'
      inputs:
        connectionType: 'None' # Ajanın kendi kimliğini kullan
        namespace: '$(namespace)'
        command: 'apply'
        arguments: '-f $(kanikoFinalFile)'

    # Adım 3: Kaniko pod'unun işini bitirmesini bekle.
    - task: Kubernetes@1
      displayName: 'Wait for Kaniko Pod to Complete'
      inputs:
        connectionType: 'None'
        namespace: '$(namespace)'
        command: 'wait'
        arguments: 'pod/$(podName) --for=condition=Succeeded --timeout=10m'

    # Adım 4: Kaniko pod'unun loglarını göster (hata ayıklama için).
    - task: Kubernetes@1
      displayName: 'Get Kaniko Pod Logs'
      inputs:
        connectionType: 'None'
        namespace: '$(namespace)'
        command: 'logs'
        arguments: '$(podName)'
        failOnStdErr: false # Loglarda hata olsa bile pipeline'ı durdurma

    # Adım 5: İşi biten Kaniko pod'unu silerek cluster'ı temizle.
   