# azure-pipelines.yml
# 'resources' bloğu en üst seviyeye (root) taşınmış son ve doğru hali.

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'user_service/*'
      - 'ticket_service/*'
      - 'auth_service/*'
      - 'frontend/*'
    exclude:
      - README.md

pool:
  name: 'Default'

variables:
  harborRepo: 'harbor.cloudpro.com.tr/helpdesk' 
  imageTag: '$(Build.BuildId)'
  k8sNamespace: 'ado-agents'
  gitRepoUrl: 'https://dev.azure.com/umutcelik0234/HelpDesk_App/_git/helpdesk-app-src'
  kanikoTemplateFile: 'kaniko-pod-template.yaml'
  kanikoFinalFile: '$(Build.ArtifactStagingDirectory)/kaniko-pod-final'

stages:
- stage: Build_Services
  displayName: 'Build and Push Service Images'
  # 'resources' bloğu buradan kaldırıldı.
  jobs:
  - job: DetectChanges
    displayName: '1. Detect Changed Services'
    steps:
      - checkout: self
        fetchDepth: 0
      - task: Bash@3
        name: detect_changes_step 
        displayName: 'Run change detection script'
        inputs:
          targetType: 'inline'
          script: |
            chmod +x templates/detect-changes.sh
            ./templates/detect-changes.sh

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'user_service'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.USER_SERVICE_CHANGED'], 'true')

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'ticket_service'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.TICKET_SERVICE_CHANGED'], 'true')

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'auth_service'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.AUTH_SERVICE_CHANGED'], 'true')

  - template: templates/build-service-job.yml
    parameters:
      serviceName: 'frontend'
      dependsOn: DetectChanges
      condition: eq(dependencies.DetectChanges.outputs['detect_changes_step.FRONTEND_CHANGED'], 'true')