# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'user_service/*' # Sadece user_service klasöründe değişiklik olunca tetiklenir

pool:
  name: 'Default' # RKE2 üzerine kurduğun ajanın pool adı

variables:
  # Azure DevOps'ta oluşturduğun Harbor Service Connection'ının adı
  harborConnection: 'HarborServiceConnection' 

  # Harbor'daki proje ve imaj adı
  imageRepository: 'helpdesk/user-service' 

  # Her build için benzersiz bir etiket
  imageTag: '$(Build.BuildId)' 

stages:
- stage: Build
  displayName: 'Build and Push Service to Harbor'
  jobs:
  - job: BuildJob
    displayName: 'Build $(imageRepository)'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: $(harborConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/user_service/Dockerfile' # user_service'in Dockerfile'ını bul
        tags: |
          $(imageTag)