# docker-compose.yml DOSYASININ TAM VE DÜZELTİLMİŞ HALİ

services:
  # --- Veritabanı Servisleri ---
  user-db:
    image: postgres:15-alpine
    container_name: helpdesk-user-db
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_admin
      - POSTGRES_PASSWORD=Passw0rd12.
      - POSTGRES_DB=user_db
    ports:
      - "5433:5432"
    networks: # <-- Bu veritabanı ağa dahil
      - helpdesk-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ticket-db:
    image: postgres:15-alpine
    container_name: helpdesk-ticket-db
    volumes:
      - ticket_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ticket_admin
      - POSTGRES_PASSWORD=Passw0rd12.
      - POSTGRES_DB=ticket_db
    ports:
      - "5434:5432"
    networks: # <-- Bu veritabanı ağa dahil
      - helpdesk-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_admin -d ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Backend Servisleri ---
  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    container_name: helpdesk-user-service
    environment:
      - DATABASE_URL=postgresql://user_admin:Passw0rd12.@user-db:5432/user_db
    ports:
      - "8001:8000"
    depends_on:
      user-db:
        condition: service_healthy
    networks: # <-- EKLENEN SATIRLAR
      - helpdesk-net

  ticket_service:
    build:
      context: .
      dockerfile: ./ticket_service/Dockerfile
    container_name: helpdesk-ticket-service
    environment:
      - DATABASE_URL=postgresql://ticket_admin:Passw0rd12.@ticket-db:5432/ticket_db
    ports:
      - "8000:8000"
    depends_on:
      ticket-db:
        condition: service_healthy
    networks: # <-- EKLENEN SATIRLAR
      - helpdesk-net
  
  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    container_name: helpdesk-auth-service
    ports:
      - "8002:8000"
    networks: # <-- EKLENEN SATIRLAR
      - helpdesk-net

  # --- Frontend Servisi ---
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: helpdesk-frontend
    ports:
      - "5173:80"
    depends_on:
      - user_service
      - ticket_service
      - auth_service
    networks: # <-- Bu zaten ağa dahildi
      - helpdesk-net

# --- Ağ ve Volüm Tanımları ---
networks:
  helpdesk-net:
    driver: bridge

volumes:
  user_postgres_data:
  ticket_postgres_data: