apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__ # Bu, pipeline'da değiştirilecek
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      # Bu argüman listesi pipeline'da doldurulacak
      - "--context=__CONTEXT__"
      - "--dockerfile=__DOCKERFILE__"
      - "--destination=__DESTINATION_TAG__"
      - "--destination=__DESTINATION_LATEST__"
      - "--cleanup"
    volumeMounts:
    - name: harbor-credentials-volume
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: harbor-credentials-volume
    secret:
      secretName: harbor-credentials
      items:
        - key: .dockerconfigjson
          path: config.json