# kaniko-pod-template.yaml - TLS Doğrulamasını Atlama

apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
spec:
  hostAliases:
  - ip: "10.77.3.203"
    hostnames:
    - "harbor.cloudpro.com.tr"
    - "vault.cloudpro.com.tr"
    - "keycloak.cloudpro.com.tr"
    - "argo.cloudpro.com.tr"
    - "core.harbor.domain"

  volumes:
  - name: workspace
    emptyDir: {}
  - name: harbor-credentials-volume
    secret:
      secretName: harbor-credentials
      items:
        - key: .dockerconfigjson
          path: config.json

  initContainers:
  - name: git-checkout
    image: alpine/git:latest
    env:
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    - name: GIT_REPO_URL
      value: "__CONTEXT__"
    
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      echo "Cloning repository..."
      CLONE_URL=$(echo $GIT_REPO_URL | sed "s,https://,https://$AZP_TOKEN@,")
      git clone $CLONE_URL /workspace/source
      echo "--- DEBUG (Init Container): Contents of /workspace/source (Git Repo Root) ---"
      ls -lR /workspace/source # /workspace/source altındaki her şeyi recursive listeler
      echo "--------------------------------------------------------"

    volumeMounts:
    - name: workspace
      mountPath: /workspace

  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--context=/workspace/source"
      - "--context-sub-path=__CONTEXT_SUB_PATH__"
      - "--dockerfile=/workspace/source/__CONTEXT_SUB_PATH__/Dockerfile"
      - "--destination=__DESTINATION_TAG__"
      - "--cleanup"
      - "--skip-tls-verify"
    
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: harbor-credentials-volume
      mountPath: /kaniko/.docker/
      
  restartPolicy: Never