# kaniko-pod-template.yaml
apiVersion: v1
kind: Pod
metadata:
  # Pod'un adı pipeline tarafından bu alana yazılacak
  name: __POD_NAME__
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    # Tüm Kaniko argümanları pipeline tarafından bu listeye eklenecek
    args:
      - "--context=__CONTEXT__"
      - "--dockerfile=__DOCKERFILE__"
      - "--destination=__DESTINATION_TAG__"
      - "--destination=__DESTINATION_LATEST__"
      - "--cleanup"
    volumeMounts:
    - name: harbor-credentials-volume
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: harbor-credentials-volume
    secret:
      # Harbor kimlik bilgilerini içeren secret'ın adı
      secretName: harbor-credentials 
      items:
        - key: .dockerconfigjson
          path: config.json