"""Add Comment and Attachment models

Revision ID: adfbec5c442e
Revises: a7aaa6656121
Create Date: 2025-06-08 08:37:34.550247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfbec5c442e'
down_revision: Union[str, None] = 'a7aaa6656121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_schema.tickets.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    schema='tickets_schema'
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users_schema.users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_schema.tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets_schema'
    )
    op.create_index('ix_tickets_tenant_id', 'tickets', ['tenant_id'], unique=False, schema='tickets_schema')
    op.create_foreign_key(None, 'tickets', 'companies', ['tenant_id'], ['id'], source_schema='tickets_schema', referent_schema='public')
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True), schema='users_schema')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], source_schema='users_schema', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='users_schema', type_='foreignkey')
    op.drop_column('users', 'company_id', schema='users_schema')
    op.drop_constraint(None, 'tickets', schema='tickets_schema', type_='foreignkey')
    op.drop_index('ix_tickets_tenant_id', table_name='tickets', schema='tickets_schema')
    op.drop_table('comments', schema='tickets_schema')
    op.drop_table('attachments', schema='tickets_schema')
    # ### end Alembic commands ###
