# templates/build-service-job.yml
# Herhangi bir servisin imajını build etmek için yeniden kullanılabilir iş (job) şablonu.

parameters:
- name: serviceName
  type: string
- name: dependsOn
  type: object
  default: []
- name: condition
  type: string
  default: succeeded()

jobs:
- job: Build_${{ parameters.serviceName }}
  displayName: 'Build Image for ${{ parameters.serviceName }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  
  variables:
    serviceName: ${{ parameters.serviceName }} 
  
  steps:
  - task: Bash@3
    displayName: '1. Prepare Kaniko Pod Manifest for ${{ parameters.serviceName }}'
    env:
      AZP_TOKEN: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        echo "Preparing manifest for build $(imageTag) for service: $(serviceName)..."
        
        # DÜZELTME: Pod adı için geçersiz olan '_' karakterini '-' ile değiştiriyoruz.
        # Bu, Kubernetes'in isimlendirme kuralı ihlalini çözer.
        safePodSuffix=$(echo "$(serviceName)" | sed 's/_/-/g')
        finalPodName="kaniko-build-$(imageTag)-$safePodSuffix"
        finalManifestFile="$(kanikoFinalFile)-$(serviceName)"

        cp "$(kanikoTemplateFile)" "$finalManifestFile"
        
        sed -i "s|__POD_NAME__|$finalPodName|g" "$finalManifestFile"
        sed -i "s|__CONTEXT__|$(gitRepoUrl)|g" "$finalManifestFile"
        sed -i "s|__CONTEXT_SUB_PATH__|$(serviceName)|g" "$finalManifestFile"
        sed -i "s|__DESTINATION_TAG__|$(harborRepo)/$(serviceName):$(imageTag)|g" "$finalManifestFile"
        sed -i "s|__AZP_TOKEN__|$AZP_TOKEN|g" "$finalManifestFile"
        
        echo "--- Final Kaniko Pod Manifest for $(serviceName) ---"
        cat "$finalManifestFile" | sed "s/$AZP_TOKEN/********/g"

  - task: Kubernetes@1
    displayName: '2. Apply Kaniko Pod for ${{ parameters.serviceName }}'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'apply'
      # Değişkeni burada da kullanıyoruz.
      arguments: '-f $(kanikoFinalFile)-${{ parameters.serviceName }}'
      
  - task: Kubernetes@1
    displayName: '3. Follow Logs for ${{ parameters.serviceName }}'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'logs'
      # Pod adını burada da düzeltiyoruz.
      arguments: 'pod/kaniko-build-$(imageTag)-$(echo ${{ parameters.serviceName }} | sed ''s/_/-/g'') --follow --container=kaniko'
      
  - task: Kubernetes@1
    displayName: '4. Cleanup Pod for ${{ parameters.serviceName }}'
    condition: always()
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'delete'
      # Pod adını burada da düzeltiyoruz.
      arguments: 'pod/kaniko-build-$(imageTag)-$(echo ${{ parameters.serviceName }} | sed ''s/_/-/g'') --ignore-not-found=true'