# templates/build-service-job.yml
# Herhangi bir servisin imajını build etmek için yeniden kullanılabilir iş (job) şablonu.

parameters:
- name: serviceName  # Build edilecek servisin adı (örn: 'user_service')
  type: string
- name: dependsOn    # Bu işin bağımlı olduğu önceki iş(ler)
  type: object
  default: []
- name: condition    # Bu işin çalışması için gereken koşul
  type: string
  default: succeeded()

jobs:
- job: Build_${{ parameters.serviceName }}
  displayName: 'Build Image for ${{ parameters.serviceName }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  
  variables:
    # Parametrelerden gelen servis adını, iş içinde kullanılacak bir değişkene atıyoruz.
    serviceName: ${{ parameters.serviceName }} 
  
  steps:
  - task: Bash@3
    displayName: '1. Prepare Kaniko Pod Manifest for ${{ parameters.serviceName }}'
    env:
      AZP_TOKEN: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        echo "Preparing manifest for build $(imageTag) for service: $(serviceName)..."
        cp "$(kanikoTemplateFile)" "$(kanikoFinalFile)-$(serviceName)"
        
        sed -i "s|__POD_NAME__|kaniko-build-$(imageTag)-$(serviceName)|g" "$(kanikoFinalFile)-$(serviceName)"
        sed -i "s|__CONTEXT__|$(gitRepoUrl)|g" "$(kanikoFinalFile)-$(serviceName)"
        sed -i "s|__CONTEXT_SUB_PATH__|$(serviceName)|g" "$(kanikoFinalFile)-$(serviceName)"
        sed -i "s|__DESTINATION_TAG__|$(harborRepo)/$(serviceName):$(imageTag)|g" "$(kanikoFinalFile)-$(serviceName)"
        sed -i "s|__AZP_TOKEN__|$AZP_TOKEN|g" "$(kanikoFinalFile)-$(serviceName)"
        
        echo "--- Final Kaniko Pod Manifest for $(serviceName) ---"
        cat "$(kanikoFinalFile)-$(serviceName)" | sed "s/$AZP_TOKEN/********/g"

  - task: Kubernetes@1
    displayName: '2. Apply Kaniko Pod for ${{ parameters.serviceName }}'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'apply'
      arguments: '-f $(kanikoFinalFile)-$(serviceName)'
      
  - task: Kubernetes@1
    displayName: '3. Follow Logs for ${{ parameters.serviceName }}'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'logs'
      arguments: 'pod/kaniko-build-$(imageTag)-$(serviceName) --follow --container=kaniko'
      
  - task: Kubernetes@1
    displayName: '4. Cleanup Pod for ${{ parameters.serviceName }}'
    condition: always()
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'delete'
      arguments: 'pod/kaniko-build-$(imageTag)-$(serviceName) --ignore-not-found=true'