# templates/build-service-job.yml
# PodInitializing hatasını çözen son sürüm.

parameters:
- name: serviceName
  type: string
- name: dependsOn
  type: object
  default: []
- name: condition
  type: string
  default: succeeded()

jobs:
- job: Build_${{ parameters.serviceName }}
  displayName: 'Build Image for ${{ parameters.serviceName }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  
  variables:
    serviceName: ${{ parameters.serviceName }} 
  
  steps:
  - task: Bash@3
    name: PrepareManifest
    displayName: '1. Prepare Kaniko Pod Manifest for ${{ parameters.serviceName }}'
    env:
      AZP_TOKEN: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        echo "Preparing manifest for build $(imageTag) for service: $(serviceName)..."
        safePodSuffix=$(echo "$(serviceName)" | sed 's/_/-/g')
        finalPodName="kaniko-build-$(imageTag)-$safePodSuffix"
        echo "##vso[task.setvariable variable=safePodName]$finalPodName"
        finalManifestFile="$(kanikoFinalFile)-$(serviceName)"
        cp "$(kanikoTemplateFile)" "$finalManifestFile"
        sed -i "s|__POD_NAME__|$finalPodName|g" "$finalManifestFile"
        sed -i "s|__CONTEXT__|$(gitRepoUrl)|g" "$finalManifestFile"
        sed -i "s|__CONTEXT_SUB_PATH__|$(serviceName)|g" "$finalManifestFile"
        sed -i "s|__DESTINATION_TAG__|$(harborRepo)/$(serviceName):$(imageTag)|g" "$finalManifestFile"
        sed -i "s|__AZP_TOKEN__|$AZP_TOKEN|g" "$finalManifestFile"
        echo "--- Final Kaniko Pod Manifest for $(serviceName) ---"
        cat "$finalManifestFile" | sed "s/$AZP_TOKEN/********/g"

  - task: Kubernetes@1
    displayName: '2. Apply Kaniko Pod for ${{ parameters.serviceName }}'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'apply'
      arguments: '-f $(kanikoFinalFile)-${{ parameters.serviceName }}'
      
  # YENİ ADIM: Önce initContainer'ın loglarını takip ederek bitmesini bekliyoruz.
  - task: Kubernetes@1
    displayName: '3a. Wait for Init Container (git-checkout) to Complete'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'logs'
      # '--container' (veya -c) bayrağı ile hangi konteynerin logunu istediğimizi belirtiyoruz.
      arguments: 'pod/$(safePodName) --follow --container=git-checkout'

  - task: Kubernetes@1
    displayName: '3b. Follow Logs for Main Container (kaniko)'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'logs'
      arguments: 'pod/$(safePodName) --follow --container=kaniko'
      
  - task: Kubernetes@1
    displayName: '4. Cleanup Pod for ${{ parameters.serviceName }}'
    condition: always()
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'delete'
      arguments: 'pod/$(safePodName) --ignore-not-found=true'