# templates/build-service-job.yml
# Koşul ifadeleri (condition) düzeltilmiş sürüm.

parameters:
- name: serviceName
  type: string
- name: dependsOn
  type: object
  default: []
- name: condition
  type: string
  default: succeeded()

jobs:
- job: Build_${{ parameters.serviceName }}
  displayName: 'Build Image for ${{ parameters.serviceName }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  
  variables:
    # Parametreden gelen değeri, bu işin (job) çalışma zamanı değişkenine atıyoruz.
    serviceName: ${{ parameters.serviceName }} 
  
  steps:
  
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    # DÜZELTME: 'parameters.serviceName' yerine 'variables.serviceName' kullanıyoruz.
    condition: and(succeeded(), ne(variables.serviceName, 'frontend'))
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - task: NodeTool@0
    displayName: 'Use Node.js 20.x'
    # DÜZELTME: 'parameters.serviceName' yerine 'variables.serviceName' kullanıyoruz.
    condition: and(succeeded(), eq(variables.serviceName, 'frontend'))
    inputs:
      versionSpec: '20.x'

  - task: Bash@3
    displayName: 'Install Dependencies & Run SCA Scan for ${{ parameters.serviceName }}'
    inputs:
      targetType: 'inline'
      script: |
        set -e
        cd $(Pipeline.Workspace)/s/${{ parameters.serviceName }}
        echo "Service directory: $(pwd)"
        echo "Installing dependencies and running SCA scan..."
        if [[ "${{ parameters.serviceName }}" == "frontend" ]]; then
          echo "Installing npm dependencies..."
          npm ci
          echo "Scanning for vulnerabilities with npm audit..."
          npm audit --audit-level=high || (echo "npm audit found vulnerabilities" && exit 1)
        else
          echo "Installing pip dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Scanning for vulnerabilities with pip-audit..."
          pip install pip-audit
          pip-audit -r requirements.txt --fail-on HIGH
        fi
        echo "SCA Scan completed successfully. No high or critical vulnerabilities found."

  # ... (Diğer tüm adımlar aynı kalır, değişiklik yok) ...
  - task: Bash@3
    name: PrepareManifest
    displayName: 'Prepare Kaniko Pod Manifest for ${{ parameters.serviceName }}'
    env:
      AZP_TOKEN: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        echo "Preparing manifest for build $(imageTag) for service: $(serviceName)..."
        safePodSuffix=$(echo "$(serviceName)" | sed 's/_/-/g')
        finalPodName="kaniko-build-$(imageTag)-$safePodSuffix"
        echo "##vso[task.setvariable variable=safePodName]$finalPodName"
        finalManifestFile="$(kanikoFinalFile)-$(serviceName)"
        cp "$(kanikoTemplateFile)" "$finalManifestFile"
        sed -i "s|__POD_NAME__|$finalPodName|g" "$finalManifestFile"
        sed -i "s|__CONTEXT__|$(gitRepoUrl)|g" "$finalManifestFile"
        sed -i "s|__CONTEXT_SUB_PATH__|$(serviceName)|g" "$finalManifestFile"
        sed -i "s|__DESTINATION_TAG__|$(harborRepo)/$(serviceName):$(imageTag)|g" "$finalManifestFile"
        sed -i "s|__AZP_TOKEN__|$AZP_TOKEN|g" "$finalManifestFile"
        echo "--- Final Kaniko Pod Manifest for $(serviceName) ---"
        cat "$finalManifestFile" | sed "s/$AZP_TOKEN/********/g"

  - task: Kubernetes@1
    displayName: 'Apply Kaniko Pod for ${{ parameters.serviceName }}'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'apply'
      arguments: '-f $(kanikoFinalFile)-${{ parameters.serviceName }}'
      
  - task: Kubernetes@1
    displayName: 'Wait for Init Container (git-checkout) to Complete'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'logs'
      arguments: 'pod/$(safePodName) --follow --container=git-checkout'

  - task: Kubernetes@1
    displayName: 'Follow Logs for Main Container (kaniko)'
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'logs'
      arguments: 'pod/$(safePodName) --follow --container=kaniko'
      
  - task: Kubernetes@1
    displayName: 'Cleanup Pod for ${{ parameters.serviceName }}'
    condition: always()
    inputs:
      connectionType: 'None'
      namespace: '$(k8sNamespace)'
      command: 'delete'
      arguments: 'pod/$(safePodName) --ignore-not-found=true'