apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: nexus-publisher
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  containers:
  - name: publisher
    image: umut98/nexus-publisher:latest
    env:
    - name: NEXUS_USERNAME
      value: __NEXUS_USERNAME__
    - name: NEXUS_PASSWORD
      value: __NEXUS_PASSWORD__
    - name: NEXUS_URL
      value: __NEXUS_URL__
    - name: CONTEXT_SUB_PATH # Bu path, /azp/_work/ altındaki serviceName dizini olacak
      value: __CONTEXT_SUB_PATH__
    volumeMounts:
    - name: agent-volume
      mountPath: /azp/_work/ # Agent'ın çalışma dizinini pod'a bağlamak için
    command: ["/bin/bash"] # Kabuğu başlat
    args: # Bu kabuk içinde çalışacak komutlar
    - "-c"
    - |
      set -e
      # Kaynak kod dizinine geç - YOL DÜZELTİLDİ!
      cd $(CONTEXT_SUB_PATH) 

      echo "Building Python distribution for ${{ parameters.serviceName }}..."
      pip install -r requirements.txt
      pip install wheel twine
      python setup.py sdist bdist_wheel
      
      echo "Publishing Python artifacts to Nexus hosted repository..."
      REQUESTS_VERIFY=false TWINE_USERNAME=$NEXUS_USERNAME TWINE_PASSWORD=$NEXUS_PASSWORD twine upload \
                               --repository-url $NEXUS_URL/repository/helpdesk-python-hosted/ \
                               dist/*
      echo "Python artifacts published successfully to Nexus."
  volumes:
  - name: agent-volume
    hostPath:
      path: /azp/_work/ # Bu yolu agent'ınızın çalışma dizinine göre ayarlayın
      type: DirectoryOrCreate