apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: nexus-publisher
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  hostAliases:
  - ip: "10.77.3.203"
    hostnames:
    - "sonarqube.cloudpro.com.tr"
    - "harbor.cloudpro.com.tr"
    - "vault.cloudpro.com.tr"
    - "keycloak.cloudpro.com.tr"
    - "argo.cloudpro.com.tr"
    - "nexus.cloudpro.com.tr"
  
  initContainers:
  - name: git-cloner
    image: alpine/git:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      GIT_REPO_URL_WITH_TOKEN=$(echo $GIT_REPO_URL | sed "s,https://,https://$AZP_TOKEN@,")
      echo "Cloning repository from $GIT_REPO_URL into /workspace/src..."
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/src/
      # Eğer alt dizin varsa o dizine geç
      if [ -n "$CONTEXT_SUB_PATH_RELATIVE" ]; then
        echo "Changing directory to relative path: $CONTEXT_SUB_PATH_RELATIVE"
        # Not: Bu mv komutu, eğer repo kökü doğrudan projenin kendisi değilse gereklidir.
        # Örneğin, repo -> my-monorepo/ticket_service ise ve sadece ticket_service'e gitmek istiyorsanız.
        # Eğer repo -> ticket_service ise bu satırı kaldırabilirsiniz.
        # İlk denemede bırakalım, eğer kaynak kod dizini bulunamazsa tekrar bakarız.
        mv /workspace/src/$CONTEXT_SUB_PATH_RELATIVE/* /workspace/src/ || true # Hata durumunda durma
        # rmdir /workspace/src/$CONTEXT_SUB_PATH_RELATIVE || true # Boşalan alt klasörü sil
      fi
      echo "Source code cloned successfully."
    env:
    - name: GIT_REPO_URL
      value: __GIT_REPO_URL__
    - name: AZP_TOKEN
      value: __AZP_TOKEN__
    - name: CONTEXT_SUB_PATH_RELATIVE
      value: __CONTEXT_SUB_PATH_RELATIVE__
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  containers:
  - name: publisher
    image: umut98/nexus-publisher:latest
    env:
    - name: NEXUS_USERNAME
      value: __NEXUS_USERNAME__
    - name: NEXUS_PASSWORD
      value: __NEXUS_PASSWORD__
    - name: NEXUS_URL
      value: __NEXUS_URL__
    - name: SERVICE_NAME # YENİ: serviceName'i ortam değişkeni olarak geçiriyoruz
      value: __SERVICE_NAME__
    volumeMounts:
    - name: work-volume
      mountPath: /workspace
    command: ["/bin/bash"]
    args:
    - "-c"
    - |
      set -e
      # Kaynak kod dizinine geç (şimdi doğrudan /workspace/src içinde olmalı)
      cd /workspace/src/

      echo "Building Python distribution for $SERVICE_NAME..." # DÜZELTİLDİ: $SERVICE_NAME kullanıldı
      pip install -r requirements.txt
      pip install wheel twine
      python setup.py sdist bdist_wheel
      
      echo "Publishing Python artifacts to Nexus hosted repository..."
      REQUESTS_VERIFY=false TWINE_USERNAME=$NEXUS_USERNAME TWINE_PASSWORD=$NEXUS_PASSWORD twine upload \
                               --repository-url $NEXUS_URL/repository/helpdesk-python-hosted/ \
                               dist/*
      echo "Python artifacts published successfully to Nexus."

  volumes:
  - name: work-volume
    emptyDir: {}