# templates/sbom-generator-pod-template.yaml (DÜZELTİLMİŞ)
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: sbom-generator
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  securityContext:
    fsGroup: 1001

  initContainers:
  - name: git-cloner
    image: alpine/git:latest # den referans alınarak düzeltildi
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      # AZP_TOKEN'ı doğrudan URL'ye enjekte etmek yerine git'in kendi mekanizmasını kullanmak daha güvenlidir,
      # ancak mevcut yapınız da çalışır.
      GIT_REPO_URL_WITH_TOKEN=$(echo "__GIT_REPO_URL__" | sed "s,https://,https://__AZP_TOKEN__@,")
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/source
    env:
    # Bu değişkenler Azure Pipelines tarafından doldurulur
    - name: GIT_REPO_URL
      value: "__GIT_REPO_URL__"
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  containers:
  - name: generator
    # DİKKAT: İmaj burada dinamik olarak ayarlanacak
    image: __SCANNER_IMAGE__ # Örn: node:20-slim veya python:3.11-slim
    workingDir: /workspace/source/__CONTEXT_SUB_PATH_RELATIVE__/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Preparing environment for SBOM generation..."
      
      # 1. Adım: Proje tipine göre bağımlılıkları kur
      if [ "__SERVICE_TYPE__" = "frontend" ]; then
        echo ">>> Installing npm dependencies from Nexus..."
        npm config set registry "__NPM_GROUP_URL__"
        npm install
      else
        echo ">>> Installing pip dependencies from Nexus..."
        pip install -r requirements.txt --index-url "__PYPI_GROUP_URL__" --trusted-host "__NEXUS_HOST__"
      fi

      # 2. Adım: SBOM aracını kur
      echo ">>> Installing cyclonedx-cli..."
      # Frontend ise global olarak, Python ise pip ile kurulur
      if [ "__SERVICE_TYPE__" = "frontend" ]; then
        npm install -g @cyclonedx/cdxgen
      else
        pip install cyclonedx-bom
      fi
      
      # 3. Adım: SBOM'u oluştur
      echo ">>> Generating SBOM..."
      if [ "__SERVICE_TYPE__" = "frontend" ]; then
        # Frontend için cdxgen kullanılır
        cdxgen -o /workspace/sbom.json
      else
        # Python için cyclonedx-py kullanılır
        cyclonedx-py -r -i . -o /workspace/sbom.json
      fi

      touch /workspace/generator.done
      echo ">>> SBOM generation complete."
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  # Konteyner 2: Nexus'a yükleme
  - name: uploader
    image: curlimages/curl:8.9.0
    workingDir: /workspace/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Uploader waiting for generator.done file..."
      while [ ! -f /workspace/generator.done ]; do sleep 2; done
      
      if [ -f "/workspace/sbom.json" ]; then
        echo ">>> SBOM file found. Uploading..."
        SBOM_FILE="sbom-$(date +%s)-__SERVICE_NAME__.json"
        mv /workspace/sbom.json "/workspace/$SBOM_FILE"
        curl -vS --fail -u "__NEXUS_USERNAME__:__NEXUS_PASSWORD__" \
            --upload-file "/workspace/$SBOM_FILE" \
            "http://nexus-repository-manager.nexus:8081/repository/sbom-reports/$SBOM_FILE"
        echo ">>> SBOM upload successful!"
      else
        echo ">>> No sbom.json found. Nothing to upload."
      fi
    volumeMounts:
    - name: work-volume
      mountPath: /workspace
      
  volumes:
  - name: work-volume
    emptyDir: {}