apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents # Agent'ınızın çalıştığı namespace
  labels:
    app: sbom-generator
spec:
  restartPolicy: Never # İş bitince pod'un yeniden başlamamasını sağlar
  serviceAccountName: ado-agent-sa # Kube API erişimi için önceki adımda oluşturulan SA
  initContainers:
  - name: git-cloner
    image: alpine/git:latest # Git klonlamak için
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      GIT_REPO_URL_WITH_TOKEN=$(echo $GIT_REPO_URL | sed "s,https://,https://$AZP_TOKEN@,")
      echo "Cloning repository from $GIT_REPO_URL into /workspace/src..."
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/src/
      if [ -n "$CONTEXT_SUB_PATH_RELATIVE" ]; then
        echo "Changing directory to relative path: $CONTEXT_SUB_PATH_RELATIVE"
        mv /workspace/src/$CONTEXT_SUB_PATH_RELATIVE/* /workspace/src/ || true
      fi
      echo "Source code cloned successfully."
    env:
    - name: GIT_REPO_URL
      value: __GIT_REPO_URL__
    - name: AZP_TOKEN
      value: __AZP_TOKEN__
    - name: CONTEXT_SUB_PATH_RELATIVE
      value: __CONTEXT_SUB_PATH_RELATIVE__
    volumeMounts:
    - name: work-volume
      mountPath: /workspace # Kaynak kodun klonlanacağı paylaşılan dizin

  containers:
  - name: generator
    image: umut98/sbom-generator:latest # Kendi özel imajınız buraya gelecek
    env:
    - name: NEXUS_USERNAME
      value: __NEXUS_USERNAME__
    - name: NEXUS_PASSWORD
      value: __NEXUS_PASSWORD__
    - name: NEXUS_URL
      value: "http://nexus-repository-manager.nexus:8081"
    - name: SERVICE_NAME
      value: __SERVICE_NAME__
    - name: CONTEXT_SUB_PATH_RELATIVE
      value: __CONTEXT_SUB_PATH_RELATIVE__
    volumeMounts:
    - name: work-volume
      mountPath: /workspace # Init Container'dan klonlanan kodun okunacağı yer
    command: ["/bin/bash"]
    args:
    - "-c"
    - |
      set -e
      # Hata ayıklama komutları aynı kalacak
      # ... (önceki hata ayıklama komutları) ...
      
      # --- YENİ EKLENEN SBOM HATA AYIKLAMA KOMUTLARI ---
      echo "--- SBOM Generator Hata Ayıklama Bilgisi ---"
      echo "Mevcut PATH: $PATH"
      echo "Python site-packages dizini içeriği:"
      ls -l /usr/local/lib/python3.11/site-packages/cyclonedx_bom || echo "cyclonedx_bom paket dizini bulunamadı."
      echo " cyclonedx-bom komutunun nerede olduğunu ara:"
      which cyclonedx-bom || echo "cyclonedx-bom PATH içinde bulunamadı."
      find /usr/local/bin /usr/bin -name "cyclonedx-bom" || echo "cyclonedx-bom standart bin dizinlerinde bulunamadı."
      echo "----------------------------------------------"
      # --- SBOM Hata Ayıklama Komutları Sonu ---

      cd "/workspace/src/$CONTEXT_SUB_PATH_RELATIVE/" # Doğru dizine git

      echo "Generating SBOM for $SERVICE_NAME..."
      
      if [[ "$SERVICE_NAME" == "user_service" || "$SERVICE_NAME" == "ticket_service" ]]; then
        # pip install cyclonedx-bom # Bu satırı kaldırın, Dockerfile'da yüklü
        python -m cyclonedx_bom -o sbom.json
      elif [[ "$SERVICE_NAME" == "frontend" ]]; then
        echo "Skipping SBOM for frontend in this example, adjust if needed."
        exit 0
      fi

      SBOM_FILE="sbom-$(date +%s)-$SERVICE_NAME.json"
      mv sbom.json "$SBOM_FILE"

      echo "Uploading SBOM to Nexus Raw repository..."
      curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
           --upload-file "$SBOM_FILE" \
           "$NEXUS_URL/repository/sbom-reports/$SBOM_FILE"
      echo "SBOM uploaded to Nexus."
  volumes:
  - name: work-volume
    emptyDir: {}