# templates/sbom-generator-pod-template.yaml (YENİ - Jenerik ve Dinamik Versiyon)
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: sbom-generator
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  securityContext:
    fsGroup: 1001

  initContainers:
  - name: git-cloner
    image: alpine:3.19 # Versiyon sabitlendi
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      GIT_REPO_URL_WITH_TOKEN=$(echo "__GIT_REPO_URL__" | sed "s,https://,https://__AZP_TOKEN__@,")
      echo "Cloning repository into /workspace/source..."
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/source
      echo "Source code cloned successfully."
    env:
    - name: GIT_REPO_URL
      value: "__GIT_REPO_URL__"
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  containers:
  # Bu konteynerin imajı ve komutu pipeline'dan dinamik olarak gelecek
  - name: generator
    image: __SBOM_GENERATOR_IMAGE__
    workingDir: /workspace/source/__CONTEXT_SUB_PATH_RELATIVE__/
    command: ["/bin/bash", "-c"]
    args:
    - |
      __SBOM_GENERATOR_ARGS__

    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  # uploader konteyneri aynı kalıyor, sadece 'generator' işini bitirene kadar bekliyor
  - name: uploader
    image: curlimages/curl:8.9.0 # Versiyon sabitlendi
    workingDir: /workspace/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Uploader waiting for generator.done file..."
      
      # 'generator.done' dosyası oluşana kadar bekle
      while [ ! -f /workspace/generator.done ]; do
        sleep 2
      done
      
      # Sadece sbom.json varsa yüklemeyi dene
      if [ -f "/workspace/sbom.json" ]; then
        echo ">>> SBOM file found. Preparing to upload..."
        SBOM_FILE="sbom-$(date +%s)-__SERVICE_NAME__.json"
        mv /workspace/sbom.json "/workspace/$SBOM_FILE"
        
        echo ">>> Uploading $SBOM_FILE to Nexus..."
        if ! curl -vS --fail -u "__NEXUS_USERNAME__:__NEXUS_PASSWORD__" \
            --upload-file "/workspace/$SBOM_FILE" \
            "http://nexus-repository-manager.nexus:8081/repository/sbom-reports/$SBOM_FILE"; then
          echo "!!! SBOM UPLOAD FAILED !!!"
          exit 1
        fi
        echo ">>> SBOM upload successful!"
      else
        echo ">>> No sbom.json found. Nothing to upload. Exiting gracefully."
      fi

    volumeMounts:
    - name: work-volume
      mountPath: /workspace
      
  volumes:
  - name: work-volume
    emptyDir: {}