# templates/sbom-generator-pod-template.yaml (DÜZELTİLMİŞ)
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: sbom-generator
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  securityContext:
    fsGroup: 1001

  initContainers:
  - name: git-cloner
    image: alpine/git:latest # den referans alınarak düzeltildi
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      # AZP_TOKEN'ı doğrudan URL'ye enjekte etmek yerine git'in kendi mekanizmasını kullanmak daha güvenlidir,
      # ancak mevcut yapınız da çalışır.
      GIT_REPO_URL_WITH_TOKEN=$(echo "__GIT_REPO_URL__" | sed "s,https://,https://__AZP_TOKEN__@,")
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/source
    env:
    # Bu değişkenler Azure Pipelines tarafından doldurulur
    - name: GIT_REPO_URL
      value: "__GIT_REPO_URL__"
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  containers:
  - name: generator
    image: __SCANNER_IMAGE__
    workingDir: /workspace/source/__CONTEXT_SUB_PATH_RELATIVE__/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Preparing environment for SBOM generation..."
      
      if [ "__SERVICE_TYPE__" = "frontend" ]; then
        echo ">>> Installing npm dependencies from Nexus..."
        
        echo ">>> Creating .npmrc for Nexus authentication..."
        
        # --- SBOM ADIMI İÇİN DÜZELTME BAŞLANGICI ---
        # SCA adımında başarılı olan doğrudan `.npmrc` yazma yöntemini kullanıyoruz.
        AUTH_TOKEN=$(echo -n "__NEXUS_USERNAME__:__NEXUS_PASSWORD__" | base64)
        CLEAN_NPM_REGISTRY_URL=$(echo "__NPM_GROUP_URL__" | sed 's|^https\{0,1\}://||')
        
        echo "//${CLEAN_NPM_REGISTRY_URL}:_auth=$AUTH_TOKEN" >> ./.npmrc
        echo "always-auth=true" >> ./.npmrc
        # HATALI SATIR BURADA DÜZELTİLDİ:
        echo "registry=__NPM_GROUP_URL__" >> ./.npmrc 
        # --- SBOM ADIMI İÇİN DÜZELTME SONU ---
        
        echo ">>> .npmrc file created for Nexus authentication."

        npm install
        # npm audit --audit-level=moderate || (echo "npm audit found vulnerabilities" && exit 1)
        echo "npm audit skipped in SBOM generation due to Nexus configuration."
      else
        echo ">>> Installing pip dependencies from Nexus..."
        pip install -r requirements.txt --index-url "__PYPI_GROUP_URL__" --trusted-host "__NEXUS_HOST__"
      fi
      
      echo ">>> Installing cyclonedx-cli..."
      if [ "__SERVICE_TYPE__" = "frontend" ]; then
        npm install -g @cyclonedx/cdxgen
      else
        pip install cyclonedx-bom
      fi
      
      echo ">>> Generating SBOM..."
      if [ "__SERVICE_TYPE__" = "frontend" ]; then
        /usr/local/bin/cdxgen -o /workspace/sbom.json
      else
        cyclonedx-py -r -i . -o /workspace/sbom.json
      fi

      touch /workspace/generator.done
      echo ">>> SBOM generation complete."
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  # Konteyner 2: Nexus'a yükleme
  - name: uploader
    image: curlimages/curl:8.9.0
    workingDir: /workspace/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Uploader waiting for generator.done file..."
      while [ ! -f /workspace/generator.done ]; do sleep 2; done
      
      if [ -f "/workspace/sbom.json" ]; then
        echo ">>> SBOM file found. Uploading..."
        SBOM_FILE="sbom-$(date +%s)-__SERVICE_NAME__.json"
        mv /workspace/sbom.json "/workspace/$SBOM_FILE"
        curl -vS --fail -u "__NEXUS_USERNAME__:__NEXUS_PASSWORD__" \
            --upload-file "/workspace/$SBOM_FILE" \
            "http://nexus-repository-manager.nexus:8081/repository/sbom-reports/$SBOM_FILE"
        echo ">>> SBOM upload successful!"
      else
        echo ">>> No sbom.json found. Nothing to upload."
      fi
    volumeMounts:
    - name: work-volume
      mountPath: /workspace
      
  volumes:
  - name: work-volume
    emptyDir: {}