# templates/sbom-generator-pod-template.yaml (DÜZELTİLMİŞ)
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: sbom-generator
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  securityContext:
    fsGroup: 1001

  initContainers:
  - name: git-cloner
    image: alpine/git:latest # den referans alınarak düzeltildi
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      # AZP_TOKEN'ı doğrudan URL'ye enjekte etmek yerine git'in kendi mekanizmasını kullanmak daha güvenlidir,
      # ancak mevcut yapınız da çalışır.
      GIT_REPO_URL_WITH_TOKEN=$(echo "__GIT_REPO_URL__" | sed "s,https://,https://__AZP_TOKEN__@,")
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/source
    env:
    # Bu değişkenler Azure Pipelines tarafından doldurulur
    - name: GIT_REPO_URL
      value: "__GIT_REPO_URL__"
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  containers:
  # Konteyner 1: cyclonedx-cli
  - name: generator
    image: cyclonedx/cyclonedx-cli:0.28.2
    workingDir: /workspace/source/__CONTEXT_SUB_PATH_RELATIVE__/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Generating SBOM with cyclonedx-cli..."
      cyclonedx-cli analyze . --output-file /workspace/sbom.json
      touch /workspace/generator.done
      echo ">>> SBOM generation complete."
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  # Konteyner 2: Nexus'a yükleme
  - name: uploader
    image: curlimages/curl:8.9.0
    workingDir: /workspace/
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      echo ">>> Uploader waiting for generator.done file..."
      while [ ! -f /workspace/generator.done ]; do sleep 2; done
      
      if [ -f "/workspace/sbom.json" ]; then
        echo ">>> SBOM file found. Uploading..."
        SBOM_FILE="sbom-$(date +%s)-__SERVICE_NAME__.json"
        mv /workspace/sbom.json "/workspace/$SBOM_FILE"
        curl -vS --fail -u "__NEXUS_USERNAME__:__NEXUS_PASSWORD__" \
            --upload-file "/workspace/$SBOM_FILE" \
            "http://nexus-repository-manager.nexus:8081/repository/sbom-reports/$SBOM_FILE"
        echo ">>> SBOM upload successful!"
      else
        echo ">>> No sbom.json found. Nothing to upload."
      fi
    volumeMounts:
    - name: work-volume
      mountPath: /workspace
      
  volumes:
  - name: work-volume
    emptyDir: {}