# templates/sbom-generator-pod-template.yaml
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: ado-agents
  labels:
    app: sbom-generator
spec:
  restartPolicy: Never
  serviceAccountName: ado-agent-sa
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001 
    fsGroup: 1001
  initContainers:
  - name: git-cloner
    image: alpine/git:latest
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -ex
      GIT_REPO_URL_WITH_TOKEN=$(echo "__GIT_REPO_URL__" | sed "s,https://,https://__AZP_TOKEN__@,")
      echo "Cloning repository from __GIT_REPO_URL__ into /workspace/source..."
      git clone "$GIT_REPO_URL_WITH_TOKEN" /workspace/source
      echo "Source code cloned successfully."
    env:
    - name: GIT_REPO_URL
      value: __GIT_REPO_URL__
    - name: AZP_TOKEN
      value: __AZP_TOKEN__
    volumeMounts:
    - name: work-volume
      mountPath: /workspace

  # 2. Ana Container: SBOM oluşturur ve yükler
  containers:
  - name: generator
    image: cyclonedx/cyclonedx-python:latest
    workingDir: /workspace/source/__CONTEXT_SUB_PATH_RELATIVE__/
    command: ["/bin/bash", "-c"]
    env:
    - name: NEXUS_USERNAME
      value: __NEXUS_USERNAME__
    - name: NEXUS_PASSWORD
      value: __NEXUS_PASSWORD__
    - name: NEXUS_URL
      value: "http://nexus-repository-manager.nexus:8081"
    - name: SERVICE_NAME
      value: __SERVICE_NAME__
    - name: CONTEXT_SUB_PATH_RELATIVE
      value: __CONTEXT_SUB_PATH_RELATIVE__
    volumeMounts:
    - name: work-volume
      mountPath: /workspace
    args:
    - |
      set -ex
      echo "Installing curl..."
      apt-get update && apt-get install -y curl
      echo "Generating SBOM for $SERVICE_NAME..."

      if [[ "$SERVICE_NAME" == "user_service" || "$SERVICE_NAME" == "ticket_service" ]]; then
        cyclonedx-py requirements requirements.txt -o sbom.json
      elif [[ "$SERVICE_NAME" == "frontend" ]]; then
        echo "Skipping SBOM for frontend service."
        exit 0
      else
        echo "Unknown service type: $SERVICE_NAME. Skipping SBOM generation."
        exit 0
      fi

      echo "--- Generated SBOM Preview ---"
      head -n 10 sbom.json
      echo "----------------------------"

      # SBOM dosyasını Nexus'a yüklemek için benzersiz bir isimle yeniden adlandır
      SBOM_FILE="sbom-$(date +%s)-$SERVICE_NAME.json"
      mv sbom.json "$SBOM_FILE"

      echo "Uploading SBOM '$SBOM_FILE' to Nexus Raw repository..."
      # curl komutunun başarılı olup olmadığını kontrol et
      if ! curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
          --upload-file "$SBOM_FILE" \
          "$NEXUS_URL/repository/sbom-reports/$SBOM_FILE" 2>&1 | tee curl_sbom_output.log; then
          echo "ERROR: SBOM upload failed. See curl_sbom_output.log above for details."
          echo "##vso[task.logissue type=error;]SBOM upload operation failed."
          exit 1
      fi
      cat curl_sbom_output.log
      echo "SBOM uploaded to Nexus successfully."

      exec sleep 5
  volumes:
  - name: work-volume
    emptyDir: {}
