# templates/sca-pod-template.yaml
# Tarama mantığını kendi içinde barındıran, daha akıllı pod şablonu.

apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
spec:
  volumes:
  - name: workspace
    emptyDir: {}

  initContainers:
  - name: git-checkout
    image: alpine/git:latest
    env:
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    - name: GIT_REPO_URL
      value: "__CONTEXT__"
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      CLONE_URL=$(echo $GIT_REPO_URL | sed "s,https://,https://$AZP_TOKEN@,")
      git clone $CLONE_URL /workspace/source
    volumeMounts:
    - name: workspace
      mountPath: /workspace

  containers:
  - name: scanner
    image: __SCANNER_IMAGE__
    workingDir: /workspace/source/__CONTEXT_SUB_PATH__
    # Komut artık daha karmaşık bir script'i doğrudan burada içeriyor.
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      echo "SCA Scan starting for service type: $SERVICE_TYPE"
      if [ "$SERVICE_TYPE" = "frontend" ]; then
        echo "Running Node.js SCA Scan..."
        npm install
        npm audit --audit-level=high || (echo "npm audit found vulnerabilities" && exit 1)
      else
        echo "Running Python SCA Scan..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt pip-audit
        pip-audit -r requirements.txt --fail-on HIGH
      fi
      echo "SCA Scan completed successfully."
    
    # Pipeline'dan servis tipini bir ortam değişkeni olarak alıyoruz.
    env:
    - name: SERVICE_TYPE
      value: "__SERVICE_TYPE__"

    volumeMounts:
    - name: workspace
      mountPath: /workspace/source
      
  restartPolicy: Never