# templates/sonar-pod-template.yaml
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
spec:
  # hostAliases bloğu burada kalabilir, ancak iç adres için DNS sorununu çözmek için yeterli değil.
  # Dışarıdaki FQDN için hala işe yarayabilir, şimdilik dokunmayalım.
  hostAliases:
  - ip: "10.77.3.203"
    hostnames:
    - "sonarqube.cloudpro.com.tr"
    - "harbor.cloudpro.com.tr"
    - "vault.cloudpro.com.tr"
    - "keycloak.cloudpro.com.tr"
    - "argo.cloudpro.com.tr"
    - "nexus.cloudpro.com.tr"

  volumes:
  - name: workspace
    emptyDir: {}
  - name: custom-cacerts-volume
    configMap:
      name: sonar-custom-cacerts

  initContainers:
  - name: git-checkout
    image: alpine/git:latest
    env:
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    - name: GIT_REPO_URL
      value: "__CONTEXT__"
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      cd /workspace
      CLONE_URL=$(echo $GIT_REPO_URL | sed "s,https://,https://$AZP_TOKEN@,")
      git clone $CLONE_URL .
      chown -R 1000:1000 /workspace
      chmod -R u+w /workspace
    volumeMounts:
    - name: workspace
      mountPath: /workspace

  containers:
  - name: sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:latest
    workingDir: /workspace/__CONTEXT_SUB_PATH__
    env:
      - name: SONAR_SCANNER_OPTS
        value: "-Duser.home=/tmp -Djavax.net.ssl.trustStore=/opt/java/cacerts-custom -Djavax.net.ssl.trustStorePassword=changeit"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: custom-cacerts-volume
      mountPath: /opt/java/cacerts-custom
      subPath: cacerts-custom
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      echo "--- Debugging DNS in Pod ---"
      echo "Current working directory: $(pwd)"
      echo "Content of /etc/resolv.conf:"
      cat /etc/resolv.conf
      echo "DNS Lookup for sonarqube.sonarqube.svc.cluster.local:"
      nslookup sonarqube.sonarqube.svc.cluster.local # Varsayılan servis adın ve namespace'inle değiştir
      echo "DNS Lookup for kubernetes.default.svc.cluster.local (Kubernetes API):"
      nslookup kubernetes.default.svc.cluster.local # Genel Kubernetes API erişimi
      echo "--- End Debugging DNS ---"

      echo "Starting SonarScanner with custom SSL truststore..."

      sonar-scanner \
        -Dsonar.host.url=__SONAR_URL__ \
        -Dsonar.login=__SONAR_TOKEN__ \
        -Dsonar.projectKey=__PROJECT_KEY__ \
        -Dsonar.projectName=__PROJECT_KEY__ \
        -Dsonar.sources=. \
        -Dsonar.scm.disabled=true

  restartPolicy: Never