# templates/sonar-pod-template.yaml
# NIHAI COZUM: Java'nın SSL sertifikasına güvenmesi için komutlar eklendi.
apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
spec:
  hostAliases:
  - ip: "10.77.3.203"
    hostnames:
    - "sonarqube.cloudpro.com.tr"
    - "harbor.cloudpro.com.tr"
    - "vault.cloudpro.com.tr"

  volumes:
  - name: workspace
    emptyDir: {}

  initContainers:
  - name: git-checkout
    image: alpine/git:latest
    env:
    - name: AZP_TOKEN
      value: "__AZP_TOKEN__"
    - name: GIT_REPO_URL
      value: "__CONTEXT__"
    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      cd /workspace
      CLONE_URL=$(echo $GIT_REPO_URL | sed "s,https://,https://$AZP_TOKEN@,")
      git clone $CLONE_URL .
    volumeMounts:
    - name: workspace
      mountPath: /workspace

  containers:
  - name: sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:latest
    workingDir: /workspace/__CONTEXT_SUB_PATH__
    env:
      - name: SONAR_SCANNER_OPTS
        value: "-Duser.home=/tmp"
      - name: JAVA_HOME 
        value: /usr/lib/jvm/default-jvm

    command: ["/bin/sh", "-c"]
    args:
    - |
      set -e
      echo "Importing SonarQube SSL certificate..."
      
      # OpenSSL ile sunucudan sertifikayı çek ve bir dosyaya kaydet
      openssl s_client -showcerts -connect sonarqube.cloudpro.com.tr:443 </dev/null 2>/dev/null | openssl x509 -outform PEM > /tmp/sonar.pem
      
      # DÜZELTME: 'keytool' komutundaki sertifika yolu düzeltildi.
      # Standart Java imajlarında doğru yol genellikle budur.
      keytool -import -alias sonarqube-cert -keystore $JAVA_HOME/lib/security/cacerts -file /tmp/sonar.pem -storepass changeit -noprompt
      
      echo "Certificate imported. Starting SonarScanner..."
      
      # Şimdi tarayıcıyı normal şekilde çalıştır
      sonar-scanner \
        -Dsonar.host.url=__SONAR_URL__ \
        -Dsonar.login=__SONAR_TOKEN__ \
        -Dsonar.projectKey=__PROJECT_KEY__ \
        -Dsonar.projectName=__PROJECT_KEY__ \
        -Dsonar.sources=. \
        -Dsonar.scm.disabled=true

  restartPolicy: Never