"""create initial ticket service tables

Revision ID: 9f6b040c1106
Revises: 
Create Date: 2025-06-08 17:43:10.382292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6b040c1106'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets_schema'
    )
    op.create_index(op.f('ix_tickets_schema_tickets_status'), 'tickets', ['status'], unique=False, schema='tickets_schema')
    op.create_index(op.f('ix_tickets_schema_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False, schema='tickets_schema')
    op.create_index(op.f('ix_tickets_schema_tickets_title'), 'tickets', ['title'], unique=False, schema='tickets_schema')
    op.create_index('ix_tickets_tenant_id', 'tickets', ['tenant_id'], unique=False, schema='tickets_schema')
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_schema.tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    schema='tickets_schema'
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_schema.tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tickets_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments', schema='tickets_schema')
    op.drop_table('attachments', schema='tickets_schema')
    op.drop_index('ix_tickets_tenant_id', table_name='tickets', schema='tickets_schema')
    op.drop_index(op.f('ix_tickets_schema_tickets_title'), table_name='tickets', schema='tickets_schema')
    op.drop_index(op.f('ix_tickets_schema_tickets_tenant_id'), table_name='tickets', schema='tickets_schema')
    op.drop_index(op.f('ix_tickets_schema_tickets_status'), table_name='tickets', schema='tickets_schema')
    op.drop_table('tickets', schema='tickets_schema')
    # ### end Alembic commands ###
